#name: Summary
#
#on:
#  pull_request_target:
#    types:
#      - opened
#      - synchronize
#      - reopened
#      - edited
#
#jobs:
#  summary-check:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          ref: ${{github.event.pull_request.head.ref}}
#          repository: ${{github.event.pull_request.head.repo.full_name}}
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '16'
#          cache: 'npm'
#          cache-dependency-path: .github/test/package-lock.json
#      - run: npm install --prefix .github/test
#      - run: npm test --prefix .github/test
#
#      - uses: pascalgn/automerge-action@v0.14.3
#        env:
#          MERGE_LABELS: ""
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}

#      - name: Discord notification
#        env:
#          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#        uses: Ilshidur/action-discord@master
#        with:
#          args: 'The summary ${{github.event.pull_request.head.repo.full_name }} has been accepted.'

name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: 'Thanks ${{ github.event.head_commit.author.name }} has been submitted in ${{ steps.date.outputs.date }}'
